version: '3.8'

services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: always
    environment:
      NGROK_AUTHTOKEN: 2v79zWUP1YjCpwK37FgzRwSxA8c_35Vp79iZffaYX9fc9vpQz
    ports:
      - "4040:4040" # Ngrok Web Interface
    entrypoint: /bin/sh -c
    command: >
      ngrok http frontend:3000 --subdomain=newstudentportal &
      ngrok http backend:8000 --subdomain=newstudentportal-backend &
      wait
    depends_on:
      - frontend
      - backend

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: courses
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/courses.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"  # 🔧 Host 3307 → Container 3306

  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  frontend:
    build: ./client
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env  # Make sure this loads the client secrets into the frontend service
    depends_on:
      - backend

volumes:
  mysql_data: