version: "3.8"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile  # Dockerfile for Express API
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: student_portal
      DB_PORT: 3306
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile  # Dockerfile for Next.js
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

