version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: courses
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/courses.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}  # Ensure this environment variable is set in your environment or .env file
    volumes:
      - ./ngrok.yml:/ngrok.yml  # Map your ngrok.yml configuration file
    ports:
      - "4040:4040"
    command: ngrok start --config /ngrok.yml --all  # Start ngrok with the ngrok.yml configuration

  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - ngrok

  frontend:
    build: ./client
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - backend

volumes:
  mysql_data:
